Made settings editable
Cryptonomic/Tezori pull request #746
Opened 2022-06-20 08:29 UTC by Nike682631

This pr is in reference of the issue: https://github.com/Cryptonomic/Tezori/issues/727

2022-06-21 11:56 UTC, Nike682631 commented
https://user-images.githubusercontent.com/40403668/174793386-6af967b5-9279-405c-beee-ed4049f5328d.mp4

2022-06-21 19:42 UTC, vishakh requested changes

2022-06-21 19:42 UTC, vishakh commented on src/components/Settings.tsx
> +            id={"settings_apikey"}
Dupe

2022-06-21 19:42 UTC, vishakh commented on src/components/Settings.tsx
> +            <p>
Please pull in the latest changes from `trunk` and fix all merge conflicts. We now also display derivation paths.

2022-06-24 14:03 UTC, vishakh approved these changes

2022-06-24 14:03 UTC, merged